# Create the file with the following command
echo "name: secscrape_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - pandas=1.5.3
  - numpy=1.24.2
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - nltk=3.8.1
  - beautifulsoup4=4.12.2
  - requests=2.28.2
  - fpdf=1.7.2
  - pip:
      - sec-api==1.0.17
      - python-edgar==3.0.1
      - pysentimiento==0.7.2
      - textblob==0.17.1
      - pdfplumber==0.9.0
      - yfinance==0.2.18
      - plotly==5.14.1
      - streamlit==1.22.0" > environment.yml
